---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventorymgmtdb
    username: root
    password: MyNewPass
  jpa:
    show-sql: true
    generate-ddl: false
stock:
   transportType: air
   slaDays: 3
...
---
spring:
  profiles: test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/inventorymgmtdb'
    username: root
    password: MyNewPass
  jpa:
    show-sql: true
    generate-ddl: false
stock:
  transportType: air
  slaDays: 3
...